---
title: "Cancer Death vs Poverty by County in US"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Cancer Death vs Poverty by County in US}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=6,
  fig.height=6
)
```

```{r setup, message=FALSE}
library(tidyverse)
```

# Load data

Read directly from [this URL](https://raw.githubusercontent.com/Arnab777as3uj/STAT6021-Cancer-Prediction-Project/master/cancer_reg.csv) then rename one column.

Load data:
```{r}
cancer_reg <- readr::read_csv("https://raw.githubusercontent.com/Arnab777as3uj/STAT6021-Cancer-Prediction-Project/master/cancer_reg.csv")
```

See a summary:
```{r}
summary(cancer_reg)
```

Rename the "TARGET_deathRate" column to "cancer_death_rate":
```{r}
cancer_reg <- dplyr::rename(cancer_reg, "cancer_death_rate" = "TARGET_deathRate")
```

Make scatter plot, giving points alpha=25% opacity:
```{r}
ggplot(cancer_reg, aes(x = povertyPercent, y = cancer_death_rate)) +
  geom_point(alpha = 0.25) +
  xlab("Poverty Percentage") +
  ylab("Cancer Death Rate") +
  ggtitle("Cancer Death vs Poverty by County in US")
```

